New features added to Projview
healpy/healpy pull request #752
Opened 2022-03-23 12:51 UTC by trygvels

Hi!
I have added some missing features to the projview function. 

The new additions are
- subplots
- remove mono-dipole
- top left and right labels
- preserving tickmarkers when specifying ticklabels
- fontstyle
- tickdirection and vertical label rotation

I have also made som minor changes to existing functionality, but its up to you if you want to keep it
- Adjusted rotated graticule to match standard graticule
- Added a width argument, because overriding_plot_properties was a bit of a hassle

An example of the new features is:
```Python
hp.projview(dust, rlabel=r"A$_{\mathsf{dust}}$", llabel=r"$Q$", unit=r"$\mu$K", fontname="serif", min=-100, max=100, width=10, show_tickmarkers=True, cbar_ticks=[-100,-50, 0,50, 100], cb_orientation="vertical", sub=221, override_plot_properties={"cbar_tick_direction":"in"})
hp.projview(dust, norm="symlog", rlabel=r"A$_{\mathsf{dust}}$", llabel=r"$Q$", unit=r"$\mu$K", cbar_ticks=[-100,-50, 0,50, 100], remove_mono=True, show_tickmarkers=True,  cb_orientation="horizontal", sub=222, override_plot_properties={"cbar_tick_direction":"in"})
hp.projview(cmb,  rlabel=r"A$_{\mathrm{cmb}}$", llabel=r"$I$",  unit=r"$\mu$K",  min=-3e3, max=3e3,  cb_orientation="vertical", sub=223, graticule=True, )
hp.projview(cmb,  rlabel=r"A$_{\mathrm{cmb}}$", llabel=r"$I$", unit=r"$\mu$K", fontname="serif",  remove_dip=True, min=-300, max=300,  cb_orientation="horizontal", sub=224, graticule=True, rot_graticule=True, rot=(0,0,0))
```
Which produces:
![example](https://user-images.githubusercontent.com/21258020/159703157-74071a1a-82c3-4c28-b2a9-e56c6d0834f2.png)

**_Missing features:_**
- Currently, there is no way to use the same symlog functionality as mollview. I suspect this is a simple fix.
- I started implementing a coordinate rotation of the custom graticule, but ran out of time. This would be useful.

2022-03-23 22:02 UTC, zonca commented
@F-Tomas would you like to review this pull request?

2022-03-24 10:55 UTC, F-Tomas commented
I will try it out.

2022-03-24 14:37 UTC, trygvels commented
I just added a 'symlog' normalization keyword for "norm" using matplotlib's library.
The new result for the test functions are thus:
```Python
hp.projview(dust, rlabel=r"A$_{\mathsf{dust}}$", llabel=r"$Q$", unit=r"$\mu$K", fontname="serif", min=-100, max=100, width=10, show_tickmarkers=True, cbar_ticks=[-100,-50, 0,50, 100], cb_orientation="vertical", sub=221, override_plot_properties={"cbar_tick_direction":"in"})
hp.projview(dust, norm="symlog", rlabel=r"A$_{\mathsf{dust}}$", llabel=r"$Q$", unit=r"$\mu$K", cbar_ticks=[-100,-50, 0,50, 100], remove_mono=True, show_tickmarkers=True,  cb_orientation="horizontal", sub=222, override_plot_properties={"cbar_tick_direction":"in"})
hp.projview(cmb,  rlabel=r"A$_{\mathrm{cmb}}$", llabel=r"$I$",  unit=r"$\mu$K",  min=-3e3, max=3e3,  cb_orientation="vertical", sub=223, graticule=True, )
hp.projview(cmb,  rlabel=r"A$_{\mathrm{cmb}}$", llabel=r"$I$", unit=r"$\mu$K", fontname="serif",  remove_dip=True, min=-300, max=300,  cb_orientation="horizontal", sub=224, graticule=True, rot_graticule=True, rot=(0,0,0))
```

![Uploading example.png…]()

2022-03-24 17:42 UTC, trygvels commented
I just added another symlog normalization similar to that used by Planck, from https://github.com/zonca/paperplots i believe.
It can be used by typing norm="symlog2".
If you don't want this, just let me know and ill remove it.

2022-03-24 18:02 UTC, zonca commented
thanks @trygvels 
does this allow to use the actual planck colormap in `projview`? that would be a nice feature!

2022-03-24 19:18 UTC, trygvels commented
![microwave_sky_reduced](https://user-images.githubusercontent.com/21258020/159993628-d7de34f3-11dd-497e-9d75-9334eceb2ba3.gif)
Oh yes :sunglasses:

2022-03-25 01:20 UTC, zonca commented
Nice! do you have a notebook for that I can add to the docs?

2022-03-25 10:03 UTC, trygvels commented
Do you mean for all of the new features, or just for this one?
I can make one for the new features if you would like, if its just for this one, 
I have attached the code for this particular gif underneath, and it should work if you have the colormap stored.
```Python
    import os
    import numpy as np
    import matplotlib.pyplot as plt
    import healpy as hp
    import imageio
    import cosmoglobe as cg
    import astropy.units as u

    cmap_path = Path(data_dir.__path__[0]) / "planck_cmap_logscale.dat"
    planck_cmap = np.loadtxt(cmap_path) / 255.0
    cmap = ListedColormap(planck_cmap, "planck")

    # Get data from Cosmoglobe
    chain = cg.get_test_chain()
    sky = cg.model_from_chain(
        chain,
        nside=512,
    )
    sky.remove_dipole(30 * u.deg) # Remove monopole from CMB component

    # Plot frequencies
    filenames = []
    nus = np.logspace(np.log10(1), np.log10(800), num=50, dtype=int)
    for i, freq in enumerate(nus):
        fsky = sky(freq * u.GHz, output_unit="uK_CMB")[0].value
        img = hp.projview(
            fsky,
            cbar_ticks=[-1e3, -100, -10, 0, 10, 100, 1e3, 1e5, 1e7],
            norm="symlog2",
            cmap=cmap,
            rlabel=f"{freq} GHz",
            unit=r"$\mu K_{cmb}$",
        )

        # Save figure
        fn = f"microwavegif_{i:02d}.png"
        filenames.append(fn)
        plt.savefig(fn, bbox_inches="tight", pad_inches=0.02, dpi=70)
        plt.close()

    # build gif
    with imageio.get_writer("microwave_sky_lowres.gif", mode="I", fps=10) as writer:
        for filename in filenames:
            image = imageio.imread(filename)
            writer.append_data(image)

    # Remove files
    for filename in set(filenames):
        os.remove(filename)
```
And as you can see, i have stored the planck logscale colormap locally.
It would be _really_ nice, if this was available in healpy.
I have the .dat files with RGBs for the WMAP and standard Planck as well, if you are interested!

2022-04-01 06:11 UTC, zonca requested changes
Thanks for your contribution!

just small suggestions for improvement:

it seems there is an issue with the `newvisu` notebook, see the log on readthedocs:

https://readthedocs.org/projects/healpy/builds/16522513/

2022-04-01 06:11 UTC, zonca commented on healpy/newvisufunc.py
> +      logarithmic color mapping, default: None (linear color mapping)
what about some detail about `symlog` and `symlog2`?

2022-04-01 06:11 UTC, zonca commented on healpy/projaxes.py
> +def symlog_backward(y,linthresh=1.0):
please run the `black` formatter so we get consistent formatting

2022-04-01 06:11 UTC, zonca commented on healpy/projaxes.py
> +    vmin, vmax, val, cmap=None, norm=None, linthresh=1, base=10, linscale=1, badcolor="gray", bgcolor="white"
I think we need a docstring here to explain `linthresh` and the other parameters. Or is there a better location?

2022-04-01 06:11 UTC, zonca commented on healpy/projaxes.py
> +            cmap0 = matplotlib.cm.get_cmap(cmap)
nice!!

2022-04-05 14:48 UTC, trygvels commented on healpy/projaxes.py
> +            cmap0 = matplotlib.cm.get_cmap(cmap)
Thanks!

2022-04-06 12:55 UTC, trygvels commented
I pushed the changes you requested now, and added a few lines to the tutorial.
I had forgotten to add the files to the manifest, but it works now! 🎉

2022-05-05 05:18 UTC, zonca approved these changes

2022-05-05 05:43 UTC, merged