Remove unused modules
healpy/healpy pull request #958
Opened 2024-07-21 16:30 UTC by AlexKurek

2024-07-24 15:38 UTC, lpsinger requested changes
Please update the title of this PR, as it is no longer just removing unused modules.

2024-07-24 15:38 UTC, lpsinger commented on lib/healpy/pixelfunc.py
> +    # input_ma = is_ma(m)
Why is this commented out?

2024-07-24 15:38 UTC, lpsinger commented on lib/healpy/zoomtool.py
> +            if hasattr(self, "_graton") and self._graton:
```suggestion
            if getattr(self, "_graton", False):
```

2024-07-24 15:38 UTC, lpsinger commented on test/test_sphtfunc.py
> +        # nside = 32
Why is this commented out?

2024-07-24 15:38 UTC, lpsinger commented on test/test_sphtfunc.py
> +    # lmaxmin = min(lmax, lmax_out)
Why are these commented out?

2024-07-24 16:28 UTC, AlexKurek commented on test/test_sphtfunc.py
> +        # nside = 32
Removed

2024-07-24 16:28 UTC, AlexKurek commented on lib/healpy/pixelfunc.py
> +    # input_ma = is_ma(m)
Removed.

2024-07-24 16:28 UTC, AlexKurek commented on test/test_sphtfunc.py
> +    # lmaxmin = min(lmax, lmax_out)
Removed.

2024-07-24 16:29 UTC, AlexKurek commented
Applied suggestions in https://github.com/healpy/healpy/pull/958/commits/91e1ef1d276edf0ee6ad33c50f7adcb4757d2253

2024-07-24 16:40 UTC, lpsinger requested changes
Readthedocs build is failing. Please fix.

2024-08-07 14:17 UTC, lpsinger commented
The readthedocs build is still failing.

2024-08-08 19:43 UTC, lpsinger approved these changes
LGTM assuming the CI pipeline succeeds. Over to you, @zonca.

2024-08-08 20:57 UTC, zonca approved these changes

2024-08-09 00:47 UTC, merged